name: healthy-brain-network
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - ipykernel
  - scikit-learn
  - pandas
  - seaborn 
  - nibabel 
  - nilearn
  - plotly
  - h5py
  - deepdish
  - umap-learn
  - imbalanced-learn
  - sentence-transformers
  - openpyxl
  - tabulate
  - dcor
  - hdbscan
  - bertopic
  - click
  - nbformat
  - Openai
  - gensim
  - pip:
    - pydra-ml
